config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :families
  resources :guests
  resources :sponsors
  get '/invite_family', to: 'families#index'
  get '/invite_guest', to: 'guests#index'
  get '/invite_sponsor', to: 'sponsors#index'
  get '/index', to: 'home#index'
  get '/sponsor_invites', to: 'home#sponsor_invites'
  get '/guest_invites', to: 'home#guest_invites'
  get '/family_invites', to: 'home#family_invites'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def new
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)
    @family.type_invite = 'Familia'

    respond_to do |format|
      if @family.save
        format.html { redirect_to invite_family_path, notice: 'Sua presença foi confirmada!' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_family
    @family = Family.find(params[:id])
  end

  def family_params
    params.require(:family).permit(:name)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.type_invite = 'Convidado'

    respond_to do |format|
      if @guest.save
        format.html { redirect_to invite_guest_path, notice: 'Sua presença foi confirmada!' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_guest
    @guest = Guest.find(params[:id])
  end

  def guest_params
    params.require(:guest).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @invites = Sponsor.all + Guest.all + Family.all
    else
      redirect_to new_user_session_path
    end
  end

  def sponsor_invites
    if user_signed_in?
      @invites = Sponsor.all
    else
      redirect_to new_user_session_path
    end
  end

  def guest_invites
    if user_signed_in?
      @invites = Guest.all
    else
      redirect_to new_user_session_path
    end
  end

  def family_invites
    if user_signed_in?
      @invites = Family.all
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def new
    @sponsor = Sponsor.new
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)
    @sponsor.type_invite = 'Padrinho'

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to invite_sponsor_path, notice: 'Sua presença foi confirmada!' }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_sponsor
    @sponsor = Sponsor.find(params[:id])
  end

  def sponsor_params
    params.require(:sponsor).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
  <% if f.object.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= pluralize(f.object.errors.count, "error") %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Digite o nome dos Familiares", class: "control-label" %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/families/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "families/form", family: @family %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/families/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="invite">
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <div class="image-container mb-4">
              <%= image_tag("family_invite.webp") %>
            </div>
            <div class="text-center">
              <%= link_to 'Confirmar presença', new_family_path, "data-controller":"invite-modal", class: 'btn btn-primary' %>
              <%= link_to 'Localização', "https://www.google.com/maps/place/Joa%C3%A7aba,+State+of+Santa+Catarina,+Brazil/@-27.174469,-51.505182,17z/data=!4m6!3m5!1s0x94e3faab3e246e29:0x76930ccaad948e2a!8m2!3d-27.1743773!4d-51.5054475!16zL20vMGM5MWR3?hl=en&entry=ttu", class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </body>
    </html>

app/views/families/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "families/form_modal", locals: { family: @family } %>
<% end %>

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if f.object.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= pluralize(f.object.errors.count, "error") %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Digite o nome do convidado", class: "control-label" %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/guests/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "guests/form", guest: @guest %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/guests/family_invite.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.5.0/css/bootstrap.min.css">
  </head>
  <body>
    <div class="invite">
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <div class="image-container mb-4">
              <%= image_tag("family_invite.jpg") %>
            </div>
            <div class="text-center">
              <%= link_to 'Confirmar presença', guests_new_family_presence_path, class: 'btn btn-primary' %>
              <%= link_to 'Localização', "https://www.google.com/maps/place/Joa%C3%A7aba,+State+of+Santa+Catarina,+Brazil/@-27.174469,-51.505182,17z/data=!4m6!3m5!1s0x94e3faab3e246e29:0x76930ccaad948e2a!8m2!3d-27.1743773!4d-51.5054475!16zL20vMGM5MWR3?hl=en&entry=ttu", class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.5.0/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/guests/guest_invite.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.5.0/css/bootstrap.min.css">
  </head>
  <body>
    <div class="invite">
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <div class="image-container mb-4">
              <%= image_tag("guest_invite.jpg") %>
            </div>
            <div class="text-center">
              <%= link_to 'Confirmar presença', guests_new_guest_presence_path, class: 'btn btn-primary' %>
              <%= link_to 'Localização', "https://www.google.com/maps/place/Joa%C3%A7aba,+State+of+Santa+Catarina,+Brazil/@-27.174469,-51.505182,17z/data=!4m6!3m5!1s0x94e3faab3e246e29:0x76930ccaad948e2a!8m2!3d-27.1743773!4d-51.5054475!16zL20vMGM5MWR3?hl=en&entry=ttu", class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.5.0/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/guests/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="invite">
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <div class="image-container mb-4">
              <%= image_tag("guest_invite.webp") %>
            </div>
            <div class="text-center">
              <%= link_to 'Confirmar presença', new_guest_path, "data-controller":"invite-modal", class: 'btn btn-primary' %>
              <%= link_to 'Localização', "https://www.google.com/maps/place/Joa%C3%A7aba,+State+of+Santa+Catarina,+Brazil/@-27.174469,-51.505182,17z/data=!4m6!3m5!1s0x94e3faab3e246e29:0x76930ccaad948e2a!8m2!3d-27.1743773!4d-51.5054475!16zL20vMGM5MWR3?hl=en&entry=ttu", class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </body>
    </html>

app/views/guests/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "guests/form_modal", locals: { guest: @guest } %>
<% end %>

app/views/guests/sponsor_invite.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.5.0/css/bootstrap.min.css">
  </head>
  <body>
    <div class="invite">
      <div class="container">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <div class="image-container mb-4">
              <%= image_tag("sponsor_invite.jpg") %>
            </div>
            <div class="text-center">
              <%= link_to 'Confirmar presença', guests_new_sponsor_presence_path, class: 'btn btn-primary' %>
              <%= link_to 'Localização', "https://www.google.com/maps/place/Joa%C3%A7aba,+State+of+Santa+Catarina,+Brazil/@-27.174469,-51.505182,17z/data=!4m6!3m5!1s0x94e3faab3e246e29:0x76930ccaad948e2a!8m2!3d-27.1743773!4d-51.5054475!16zL20vMGM5MWR3?hl=en&entry=ttu", class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.5.0/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>

app/views/home/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; MasterShow 2023</span>
    </div>
  </div>
</footer>

app/views/home/_index.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Todo Robot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield :javascript %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <%= render 'sidebar'%>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render 'topbar' %>
          <div class="container-fluid">
            <table class="table table-hover">
              <thead>
                <th>Nome</th>
                <th>Tipo de Convite</th>
              </thead>
              <tbody>
                <% @invites.each do |invite| %>
                  <tr>
                    <td class="text-truncate" style="max-width: 300px;"><%= invite.name %></td>
                    <td><%= invite.type_invite %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= yield %>
          </div>
        </div>
        <%=render 'footer'%>
      </div>
    </div>
    <%= turbo_frame_tag "bootstrap_modal" %>
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  </body>
</html>

app/views/home/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= defined?(index_path) && user_signed_in? ? index_path : '#' %>">
    <div class="sidebar-brand-icon">
      <i class="fas fa-user-lock"></i>
    </div>
    <div class="sidebar-brand-text mx-2">Área Restrita</div>
  </a>
  <hr class="sidebar-divider my-0">
  <% if user_signed_in? %>
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne"
        aria-expanded="true" aria-controls="collapseOne">
        <i class="fas fa-user"></i>
        <span>Lista de Convidados</span>
      </a>
      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <%= link_to index_path, class: "collapse-item" do %>
            <span>Todos</span>
          <% end %>
          <%= link_to family_invites_path, class: "collapse-item" do %>
            <span>Familia</span>
          <% end %>
          <%= link_to sponsor_invites_path, class: "collapse-item" do %>
            <span>Padrinho</span>
          <% end %>
          <%= link_to guest_invites_path, class: "collapse-item" do %>
            <span>Convidado</span>
          <% end %>
        </div>
      </div>
    </li>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-link"></i>
        <span>Links</span>
      </a>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <%= link_to invite_family_path, class: "collapse-item" do %>
            <span>Familia</span>
          <% end %>
          <%= link_to invite_sponsor_path, class: "collapse-item" do %>
            <span>Padrinho</span>
          <% end %>
          <%= link_to invite_guest_path, class: "collapse-item" do %>
            <span>Convidado</span>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/home/_topbar.html.erb
</nav>
<nav class="navbar navbar-light bg-white topbar mb-4 static-top shadow">
  <ul class="navbar-nav ml-auto">
    <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-primary mr-2" %>
  </ul>
</nav>

app/views/home/family_invites.html.erb
<%= render 'index' %>

app/views/home/guest_invites.html.erb
<%= render 'index' %>

app/views/home/index.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>Todo Robot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield :javascript %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <%= render 'sidebar'%>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render 'topbar' %>
          <div class="container-fluid">
            <table class="table table-hover">
              <thead>
                <th>Nome</th>
                <th>Tipo de Convite</th>
              </thead>
              <tbody>
                <% @sponsors.each do |sponsor| %>
                  <tr>
                    <td class="text-truncate" style="max-width: 300px;"><%= sponsor.name %></td>
                    <td><%= sponsor.type_invite %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= yield %>
          </div>
        </div>
        <%=render 'footer'%>
      </div>
    </div>
    <%= turbo_frame_tag "bootstrap_modal" %>
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  </body>
</html>

app/views/home/sponsor_invites.html.erb
<%= render 'index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetGuest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= yield :javascript %>
  </head>
  <body id="page-top">
    <%= yield %>
    <%= turbo_frame_tag "bootstrap_modal" %>
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  </body>
</html>

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if f.object.errors.any? %>
    <div class="alert alert-danger">
      <strong>Error:</strong> <%= pluralize(f.object.errors.count, "error") %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Digite o nome dos Padrinhos", class: "control-label" %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/sponsors/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "sponsors/form", sponsor: @sponsor %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sponsors/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      .invite {
        margin: 20px;
        position: relative;
      }

      .invite-image-container {
        text-align: center;
      }

      .invite-image {
        max-width: 100%;
        width: 300px; /* Defina o tamanho desejado para a imagem */
        height: auto; /* Mantém a proporção da imagem */
      }

      .btn-container {
        position: absolute;
        top: 70%;
        left: 50%;
        transform: translate(-50%, -50%);
        display: flex; /* Dispor os botões em linha */
        justify-content: center; /* Centralizar os botões horizontalmente */
        align-items: center; /* Centralizar os botões verticalmente */
      }

      .btn-container a {
        display: block;
        width: 50px; /* Defina o tamanho desejado para os botões redondos */
        height: 50px; /* Defina o tamanho desejado para os botões redondos */
        border-radius: 50%; /* Transforma os botões em círculos */
        background-color: transparent !important; /* Botões transparentes */
        margin: 32px;
        border: 2px solid #000; /* Adiciona uma borda de 2px sólida de cor preta aos botões */
      }

      @media (max-width: 767px) {
        .invite-image {
          max-width: 100%;
          width: 100%; /* Ajusta a largura para ocupar toda a largura da tela */
          height: auto; /* Mantém a proporção da imagem */
        }

        .btn-container {
          position: static;
          transform: none;
          margin-top: 10px;
          flex-direction: column; /* Dispor os botões em coluna em telas menores */
          align-items: center; /* Centralizar os botões verticalmente em telas menores */
        }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="invite">
        <div class="row">
          <div class="col-sm-12">
            <div class="invite-image-container mb-4">
              <%= image_tag("sponsor_invite.webp", class: "invite-image") %>
              <div class="btn-container">
                <%= link_to '', new_sponsor_path, "data-controller":"invite-modal", class: 'btn btn-primary' %>
                <%= link_to '', "https://www.google.com/maps/place/Joa%C3%A7aba,+State+of+Santa+Catarina,+Brazil/@-27.174469,-51.505182,17z/data=!4m6!3m5!1s0x94e3faab3e246e29:0x76930ccaad948e2a!8m2!3d-27.1743773!4d-51.5054475!16zL20vMGM5MWR3?hl=en&entry=ttu", class: 'btn btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sponsors/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "sponsors/form_modal", locals: { sponsor: @sponsor } %>
<% end %>